version: "3.8"

services:
    # Nginx & PHP FPM
    app:
        container_name: soccer-teams-app
        build: .
        volumes:
            - ./:/var/www/html:rw
        ports:
            - "8080:8080"
        environment:
            APP_NAME: "Soccer Teams"
            APP_ENV: local
            APP_KEY: base64:u6b+Qeshplm7mq07Wtu80W/wOR3wMjLYBLRTqnlukBY=
            APP_URL: http://localhost:8080
            DB_HOST: db
            DB_DATABASE: soccer_teams
            DB_USERNAME: devon
            DB_PASSWORD: secret
        networks:
            - app-network
        restart: on-failure

    # MySQL Service
    db:
        image: mysql:5.7.42
        container_name: db
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: soccer_teams
            MYSQL_USER: devon
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - ./db_data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - app-network
        restart: on-failure

networks:
    app-network:
        driver: bridge

